---
title: "Prior-post"
output: html_notebook
---

LA start of Rmd with prior post checks, to be finished 

run after fitting models 
```{r}
library(bayesplot)
```

# splines 

usage: invlogit transform to get between 0 and 10 for earlier coefficients, then between 0 and 1.15 

## no shocks
```{r}
parname <- "a_sigma" 
samp <- fit$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```

 
```{r}
parname <- "a_mu" 
samp <- fit$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```

eps scale, sd of the differences
```{r}
parname <- "epsilon_scale" 
samp <- fit$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```

## shocks 
```{r}
parname <- "a_sigma" 
samp <- fits$fit[[1]]$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```



    
```{r}
parname <- "a_mu" 
samp <- fits$fit[[1]]$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```


```{r}
parname <- "epsilon_scale" 
samp <- fits$fit[[1]]$samples$draws(parname )
#mcmc_trace(samp)
mcmc_dens_overlay(samp)
```

# transition functions
```{r}
plot_life_transition <- function(fit) {
  fit$posteriors$transition_function_mean %>% 
    ggplot(aes(x = x, y = transition_function_mean)) +
    geom_lineribbon(aes(ymin = .lower, ymax = .upper)) +
    geom_line() +
    scale_fill_brewer()
}


```

```{r}
plot_life_transition(fit)
plot_life_transition(fits$fit[[1]])

```

```{r}
fit$posteriors$transition_function_mean %>% 
    ggplot(aes(x = x, y = transition_function_mean)) +
    geom_lineribbon(aes(ymin = .lower, ymax = .upper)) +
    geom_line() +
    scale_fill_brewer() +
   geom_lineribbon(data = fits$fit[[1]]$posteriors$transition_function_mean, aes(ymin = .lower, ymax = .upper)) +
    geom_line(data = fits$fit[[1]]$posteriors$transition_function_mean, color = "red") 
```


    
